/*
var tagCats = {
	"type": ["Online", "In person", "Combination"],
	"level": ["Pre-college", "Undergraduate", "Graduate", "Certificate", "Continuing Education"],
	"location": ["Boston", "Valencia, Spain", "Los Angeles", "Mexico", "Colombia", "S\u00e3o Paulo", "Santo Domingo", "Cape Verde", "Puerto Rico", "Peru", "Ecuador", "Online", "Umbria", "Other U.S. and Canadian cities", "New York City"],
	"interest": ["Arranging", "Composition", "Conducting", "Dance", "Electronic Music", "Engineering", "Entrepreneurship", "General", "Improvisation", "Liberal Arts", "Music Business", "Music Education", "Music History", "Music Tech", "Music Theater", "Music Theory, Ear Training, Harmony", "Music Therapy", "Opera", "Performance", "Production", "Scoring for Film, TV, Video Games", "Songwriting", "Sound Design"],
	"instrument": ["Bass", "Brass", "Guitar", "Percussion", "Piano", "Strings", "Voice", "Woodwinds"],
	"genre": ["Classical", "Jazz", "Latin", "Music Theater", "Pop/rock", "Roots/Bluegrass", "World/Global"],
	"timing": ["Academic year", "Quarterly", "Summer", "Varied", "Year-round"],
	"language": ["Chinese", "English", "Portuguese", "Spanish"],
	"cost": ["Cost associated", "Low or no cost"],
	"display_group": ["Bachelor of Music", "Berklee City Music", "Berklee Latino", "Berklee on the Road", "Berklee Online", "Master of Arts", "Master of Music", "Minor", "Principal Instrument", "Study Abroad", "Summer Programs"]
}
*/


var programs = [{
		"nid": "2282496",
		"title": "CRI Group",
		"path": "/node/2282496",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284696",
		"title": "Music and Society - Gender Studies Track",
		"path": "/minors/music-society-gender",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285041",
		"title": "Conducting - Music Education Track",
		"path": "/minors/conducting-music-ed",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285281",
		"title": "Performance - Guitar",
		"path": "/node/2285281",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Guitar",
		"instrument_tids": "210746",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306606",
		"title": "Master of Arts in Music Therapy",
		"path": "/graduate/master-arts-music-therapy",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Therapy",
		"interest_tids": "210686",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282516",
		"title": "Assistive Music Technology For Visually Impaired Musicians",
		"path": "/node/2282516",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284706",
		"title": "Music and Society - Africana Studies Track",
		"path": "/minors/music-society-africana",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285056",
		"title": "Conducting - Contemporary Track",
		"path": "/minors/conducting-contemporary",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285296",
		"title": "Film Scoring",
		"path": "/film-scoring/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Composition||Scoring for Film, TV, Video Games",
		"interest_tids": "210611,210706",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306611",
		"title": "Master of Music in Scoring for Film, Television, and Video Games",
		"path": "/graduate/master-music-scoring-film-television-and-video-games",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Scoring for Film, TV, Video Games",
		"interest_tids": "210706",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282921",
		"title": "Keyboard for Music Education and Music Therapy Majors",
		"path": "/node/2282921",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284711",
		"title": "English - Spoken Word/Poetry Slam/Performance Poetry Track",
		"path": "/minors/english-spoken-word",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285066",
		"title": "Global Entertainment and Music Business",
		"path": "/node/2285066",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285301",
		"title": "Electronic Production and Design",
		"path": "/electronic-production-and-design/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Electronic Music||Production||Sound Design",
		"interest_tids": "210626,210701,210716",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2324151",
		"title": "Musical Theater Writing",
		"path": "/minors/musical-theater-writing",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Composition||Music Theater||Songwriting",
		"interest_tids": "210611,210676,210711",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282936",
		"title": "Ensemble",
		"path": "/node/2282936",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284721",
		"title": "English - Literature Track",
		"path": "/minors/english-literature",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285076",
		"title": "Contemporary Performance",
		"path": "/node/2285076",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285321",
		"title": "Composition",
		"path": "/composition/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Composition",
		"interest_tids": "210611",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2325251",
		"title": "Conducting \u2013 Musical Theater Track",
		"path": "/minors/conducting-musical-theater",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282941",
		"title": "Social Science",
		"path": "/node/2282941",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284726",
		"title": "English - Creative Writing Track",
		"path": "/minors/english-creative-writing",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285081",
		"title": "Performance - Woodwind",
		"path": "/node/2285081",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Woodwinds",
		"instrument_tids": "210736",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285326",
		"title": "Majoring in Performance: Brass",
		"path": "/brass/majoring-performance-brass",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Brass",
		"instrument_tids": "210731",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2327256",
		"title": "Arranging Core",
		"path": "/core/arranging",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282946",
		"title": "Mathematics and Natural Science",
		"path": "/node/2282946",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284806",
		"title": "Drama",
		"path": "/minors/drama",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285196",
		"title": "Majoring in Performance: Voice",
		"path": "/voice/major-performance-voice",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Voice",
		"instrument_tids": "210756",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2293676",
		"title": "American Roots Music",
		"path": "/minors/american-roots-music",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "",
		"interest_tids": "",
		"instruments": "Strings",
		"instrument_tids": "210721",
		"genres": "Roots/Bluegrass",
		"genre_tids": "210761",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2327266",
		"title": "Music Technology Core",
		"path": "/core/music-tech",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282956",
		"title": "Languages",
		"path": "/node/2282956",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284811",
		"title": "Acoustics and Electronics",
		"path": "/minors/acoustics-electronics",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts||Music Tech",
		"interest_tids": "210651,210671",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285201",
		"title": "Majoring in Performance: String",
		"path": "/strings/major-performance-string",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Strings",
		"instrument_tids": "210721",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294121",
		"title": "Performance",
		"path": "/professional-performance/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2327316",
		"title": "Conducting Core",
		"path": "/core/conducting",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282966",
		"title": "English",
		"path": "/node/2282966",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285206",
		"title": "Songwriting",
		"path": "/songwriting/major",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294156",
		"title": "Instrument Repair",
		"path": "/minors/instrument-repair",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Business||Music Education",
		"interest_tids": "210656,210661",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2327321",
		"title": "Tonal Harmony and Counterpoint Core",
		"path": "/core/tonal-harmony-and-counterpoint",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282976",
		"title": "Art History",
		"path": "/node/2282976",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284826",
		"title": "History",
		"path": "/minors/history",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285211",
		"title": "Professional Music",
		"path": "/professional-music/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "General||Music Business||Performance",
		"interest_tids": "210641,210656,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294251",
		"title": "Mediterranean Music",
		"path": "/minors/mediterranean-music",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Composition||Performance",
		"interest_tids": "210611,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Latin||World/Global",
		"genre_tids": "210771,210791",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2329391",
		"title": "Graduate Internship ",
		"path": "/graduate/graduate-internship",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2268151",
		"title": "Contemporary Writing and Production ",
		"path": "/cwp/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Arranging",
		"interest_tids": "210606",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282991",
		"title": "Private Instruction - Bass",
		"path": "/node/2282991",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285216",
		"title": "Majoring in Performance: Piano",
		"path": "/piano/major-performance-piano",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Piano",
		"instrument_tids": "210751",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294256",
		"title": "Commercial Record Production",
		"path": "/minors/commercial-record-production",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Engineering||Production",
		"interest_tids": "210631,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2329396",
		"title": "Post-Master's Fellowship",
		"path": "/graduate/fellowship",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2334491",
		"title": "Master of Business Administration in Music Business",
		"path": "/graduate-program/online-mba-in-music-business",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284841",
		"title": "Audio Design for Video Games",
		"path": "/minors/audio-design-video-games.html",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Electronic Music",
		"interest_tids": "210626",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285231",
		"title": "Performance - Percussion",
		"path": "/node/2285231",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Percussion",
		"instrument_tids": "210741",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2280676",
		"title": "Conducting - Choral Track",
		"path": "/minors/conducting-choral",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2283016",
		"title": "Music Technology",
		"path": "/minors/music-technology",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Music Tech||Production",
		"interest_tids": "210671,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284846",
		"title": "Ear Training Electives",
		"path": "/node/2284846",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285241",
		"title": "Music Therapy",
		"path": "/music-therapy/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Therapy",
		"interest_tids": "210686",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2281321",
		"title": "Ear Training Core",
		"path": "/core/ear-training",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284851",
		"title": "Performance Ear Training",
		"path": "/node/2284851",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285251",
		"title": "Music Production and Engineering",
		"path": "/mpe/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Engineering||Music Tech||Production",
		"interest_tids": "210631,210671,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306586",
		"title": "Master of Music in Contemporary Performance (Global Jazz Concentration)",
		"path": "/graduate/contemporary-performance-global-jazz",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz",
		"genre_tids": "210766",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2281341",
		"title": "Harmony Core",
		"path": "/core/harmony",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285011",
		"title": "Harmony Electives",
		"path": "/node/2285011",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285256",
		"title": "Music Education",
		"path": "/music-education/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Education",
		"interest_tids": "210661",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306591",
		"title": "Master of Music in Contemporary Performance (Production Concentration)",
		"path": "/graduate/master-music-contemporary-performance-production-concentration",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Performance||Production",
		"interest_tids": "210696,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2281351",
		"title": "Basic Keyboard",
		"path": "/node/2281351",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285016",
		"title": "Performance Studies ",
		"path": "/node/2285016",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285271",
		"title": "Music Business/Management ",
		"path": "/music-business-management/major",
		"display_group": "Misc",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Business",
		"interest_tids": "210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306596",
		"title": "Master of Arts in Global Entertainment and Music Business",
		"path": "/graduate/master-arts-global-entertainment-and-music-business",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Music Business",
		"interest_tids": "210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2282036",
		"title": "Liberal Arts",
		"path": "/node/2282036",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284226",
		"title": "Music and Society - Global Studies Track",
		"path": "/minors/music-society-global",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285031",
		"title": "Instrumental Labs - Bass",
		"path": "/node/2285031",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2285276",
		"title": "Jazz Composition",
		"path": "/jazz-composition/major",
		"display_group": "Misc",
		"levels": "",
		"level_tids": "",
		"locations": "",
		"location_tids": "",
		"interests": "",
		"interest_tids": "",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "",
		"timing_tids": "",
		"languages": "",
		"language_tids": "",
		"costs": "",
		"cost_tids": "",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2306601",
		"title": "Master of Music in Music Production, Technology, and Innovation",
		"path": "/graduate/master-music-production-technology-and-innovation",
		"display_group": "Misc",
		"levels": "Graduate",
		"level_tids": "210516",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Engineering||Music Tech||Production",
		"interest_tids": "210631,210671,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2280656",
		"title": "Majoring in Performance: Bass",
		"path": "/bass/major-performance-bass",
		"display_group": "Principal Instrument",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Bass",
		"instrument_tids": "210726",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284821",
		"title": "Philosophy",
		"path": "/minors/philosophy",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284831",
		"title": "Video Game Scoring ",
		"path": "/minors/video-game-scoring",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Scoring for Film, TV, Video Games",
		"interest_tids": "210706",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2283011",
		"title": "Performance Studies in Latin Music",
		"path": "/minors/performance-studies-latin-music",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Latin",
		"genre_tids": "210771",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294266",
		"title": "Theory of Jazz and Popular Song ",
		"path": "/minors/theory-jazz-popular-song",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts||Music Theory, Ear Training, Harmony",
		"interest_tids": "210651,210681",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2294276",
		"title": "Writing for Television and New Media ",
		"path": "/minors/writing-television-new-media",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2283021",
		"title": "Recording and Production for Musicians",
		"path": "/minors/recording-and-production-musicians",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Tech||Production",
		"interest_tids": "210671,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284211",
		"title": "Visual Culture and New Media Studies",
		"path": "/minors/visual-culture-new-media-studies",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2284221",
		"title": "Psychology",
		"path": "/minors/psychology",
		"display_group": "Minor",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Liberal Arts",
		"interest_tids": "210651",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340966",
		"title": "Online Certificates for Piano & Keyboard",
		"path": "/node/2340966",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Piano",
		"instrument_tids": "210751",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340976",
		"title": "Online Certificates for Voice",
		"path": "/node/2340976",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Piano",
		"instrument_tids": "210751",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340981",
		"title": "Online Certificates for Music Theory, Harmony, and Ear Training",
		"path": "/node/2340981",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Music Theory, Ear Training, Harmony",
		"interest_tids": "210681",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340986",
		"title": "Online Certificates for Music Business",
		"path": "/node/2340986",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Music Business",
		"interest_tids": "210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340991",
		"title": "Online Certificates for Drums",
		"path": "/node/2340991",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Percussion",
		"instrument_tids": "210741",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342371",
		"title": "Online Certificates for Music History and Liberal Arts",
		"path": "/node/2342371",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Liberal Arts||Music History",
		"interest_tids": "210651,210666",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342376",
		"title": "Online Certificates for Music for Film, TV, and Games",
		"path": "/node/2342376",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Scoring for Film, TV, Video Games",
		"interest_tids": "210706",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342381",
		"title": "Online Certificates for Arranging",
		"path": "/node/2342381",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Arranging",
		"interest_tids": "210606",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342386",
		"title": "Online Certificates for Improvisation",
		"path": "/node/2342386",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Improvisation",
		"interest_tids": "210646",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342391",
		"title": "Online Degree in Music Production ",
		"path": "/node/2342391",
		"display_group": "Berklee Online",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Engineering||Music Tech||Production",
		"interest_tids": "210631,210671,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342396",
		"title": "Online Degree in Music Business ",
		"path": "/node/2342396",
		"display_group": "Berklee Online",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Music Business",
		"interest_tids": "210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340676",
		"title": "Online Certificates for Music Production",
		"path": "/node/2340676",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Engineering||Production",
		"interest_tids": "210631,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342401",
		"title": "Online Degree in Interdisciplinary Music Studies (Create Your Own Major) ",
		"path": "/node/2342401",
		"display_group": "Berklee Online",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "General",
		"interest_tids": "210641",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340681",
		"title": "Online Certificates for Guitar",
		"path": "/node/2340681",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Guitar",
		"instrument_tids": "210746",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342406",
		"title": "Online Degree in Electronic Music Production and Sound Design ",
		"path": "/node/2342406",
		"display_group": "Berklee Online",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Electronic Music||Music Tech||Sound Design",
		"interest_tids": "210626,210671,210716",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340686",
		"title": "Online Certificates for Songwriting",
		"path": "/node/2340686",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342411",
		"title": "Online Degree in Music Composition for Film, TV, and Games",
		"path": "/node/2342411",
		"display_group": "Berklee Online",
		"levels": "Undergraduate",
		"level_tids": "210511",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Scoring for Film, TV, Video Games",
		"interest_tids": "210706",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340691",
		"title": "Online Certificates for Bass",
		"path": "/node/2340691",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Bass",
		"instrument_tids": "210726",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2340956",
		"title": "Online Certificates for Orchestration",
		"path": "/node/2340956",
		"display_group": "Berklee Online",
		"levels": "Certificate",
		"level_tids": "210521",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "Arranging||Composition||Improvisation",
		"interest_tids": "210606,210611,210646",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Quarterly",
		"timing_tids": "210806",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343301",
		"title": "Berklee India Exchange",
		"path": "/node/2343301",
		"display_group": "Berklee on the Road",
		"levels": "Pre-college||Undergraduate||Continuing Education",
		"level_tids": "210506,210511,210526",
		"locations": "Boston||India",
		"location_tids": "210531,210956",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "World/Global",
		"genre_tids": "210791",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343421",
		"title": "Berklee in Santo Domingo",
		"path": "/node/2343421",
		"display_group": "Berklee on the Road",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Dominican Republic",
		"location_tids": "210561",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343426",
		"title": "Berklee in Cape Verde",
		"path": "/node/2343426",
		"display_group": "Berklee on the Road",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Cape Verde",
		"location_tids": "210566",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343431",
		"title": "Berklee in Puerto Rico",
		"path": "/node/2343431",
		"display_group": "Berklee on the Road",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Puerto Rico",
		"location_tids": "210571",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343436",
		"title": "Berklee at Umbria Jazz Clinics",
		"path": "/node/2343436",
		"display_group": "Berklee on the Road",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Italy",
		"location_tids": "210591",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz",
		"genre_tids": "210766",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343391",
		"title": "Berklee Latino: Mexico (Performance)",
		"path": "/node/2343391",
		"display_group": "Berklee Latino",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Mexico",
		"location_tids": "210546",
		"interests": "Improvisation||Performance",
		"interest_tids": "210646,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Latin||Pop/rock",
		"genre_tids": "210766,210771,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "Spanish",
		"language_tids": "210826",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343396",
		"title": "Berklee Latino: Mexico (Songwriting and Production)",
		"path": "/node/2343396",
		"display_group": "Berklee Latino",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Mexico",
		"location_tids": "210546",
		"interests": "Production||Songwriting",
		"interest_tids": "210701,210711",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Latin||Pop/rock",
		"genre_tids": "210766,210771,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "Spanish",
		"language_tids": "210826",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343401",
		"title": "Berklee Latino: Peru",
		"path": "/node/2343401",
		"display_group": "Berklee Latino",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Peru",
		"location_tids": "210576",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Latin||Pop/rock",
		"genre_tids": "210766,210771,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "Spanish",
		"language_tids": "210826",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343406",
		"title": "Berklee Latino: Ecuador",
		"path": "/node/2343406",
		"display_group": "Berklee Latino",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Ecuador",
		"location_tids": "210581",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Latin||Pop/rock",
		"genre_tids": "210766,210771,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "Spanish",
		"language_tids": "210826",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343411",
		"title": "Berklee Latino: Colombia",
		"path": "/node/2343411",
		"display_group": "Berklee Latino",
		"levels": "Pre-college||Continuing Education",
		"level_tids": "210506,210526",
		"locations": "Colombia",
		"location_tids": "210551",
		"interests": "Improvisation||Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210646,210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Latin||Pop/rock",
		"genre_tids": "210766,210771,210781",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "Spanish",
		"language_tids": "210826",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342481",
		"title": "Berklee Global Jazz Institute Workshop at the Newport Jazz Festival",
		"path": "/node/2342481",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Other U.S. and Canadian cities",
		"location_tids": "210596",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz",
		"genre_tids": "210766",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Scholarship-based",
		"cost_tids": "210951",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343286",
		"title": "Victor Wooten/Berklee Summer Bass Workshop",
		"path": "/node/2343286",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Bass",
		"instrument_tids": "210726",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342501",
		"title": "Berklee in Los Angeles: It's All in the Song",
		"path": "/node/2342501",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Los Angeles",
		"location_tids": "210541",
		"interests": "Performance||Songwriting",
		"interest_tids": "210696,210711",
		"instruments": "Voice",
		"instrument_tids": "210756",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343291",
		"title": "Vocal Summit",
		"path": "/node/2343291",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Voice",
		"instrument_tids": "210756",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342506",
		"title": "Berklee in Los Angeles: Performance Program",
		"path": "/node/2342506",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Los Angeles",
		"location_tids": "210541",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Jazz||Pop/rock",
		"genre_tids": "210766,210781",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343296",
		"title": "Creative Entrepreneurship Summer Program",
		"path": "/node/2343296",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Entrepreneurship||Music Business",
		"interest_tids": "210636,210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342521",
		"title": "Business of Music",
		"path": "/node/2342521",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Business",
		"interest_tids": "210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342526",
		"title": "Creative Entrepreneurship Summer Program",
		"path": "/node/2342526",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Entrepreneurship||Music Business",
		"interest_tids": "210636,210656",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342531",
		"title": "Day Sessions: Young Performers Program",
		"path": "/node/2342531",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342536",
		"title": "Berklee Global String Intensive",
		"path": "/node/2342536",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Strings",
		"instrument_tids": "210721",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342541",
		"title": "Guitar Sessions",
		"path": "/node/2342541",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Guitar",
		"instrument_tids": "210746",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342546",
		"title": "Music Production Workshop",
		"path": "/node/2342546",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Electronic Music||Production||Sound Design",
		"interest_tids": "210626,210701,210716",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342551",
		"title": "Musical Theater Summer Intensive",
		"path": "/node/2342551",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Theater||Performance",
		"interest_tids": "210676,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "Music Theater",
		"genre_tids": "210776",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342556",
		"title": "Percussion Weekend",
		"path": "/node/2342556",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Percussion",
		"instrument_tids": "210741",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342561",
		"title": "Piano/Keyboard Workshop",
		"path": "/node/2342561",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Piano",
		"instrument_tids": "210751",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342571",
		"title": "Songwriting Workshop",
		"path": "/node/2342571",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Songwriting",
		"interest_tids": "210711",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342576",
		"title": "Spain Summer Performance Program",
		"path": "/node/2342576",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Valencia, Spain",
		"location_tids": "210536",
		"interests": "Engineering||Music Theory, Ear Training, Harmony||Performance||Production",
		"interest_tids": "210631,210681,210696,210701",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342466",
		"title": "Five-Week Summer Performance Program",
		"path": "/node/2342466",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343276",
		"title": "Stage Performance Workshop",
		"path": "/node/2343276",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2342471",
		"title": "Berklee Brass Program with Sean Jones",
		"path": "/node/2342471",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "Brass",
		"instrument_tids": "210731",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343281",
		"title": "Twelve-Week Full-Credit Summer Program",
		"path": "/node/2343281",
		"display_group": "Summer Programs",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Music Theory, Ear Training, Harmony||Performance",
		"interest_tids": "210681,210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Summer",
		"timing_tids": "210796",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343456",
		"title": "City Music Network",
		"path": "/node/2343456",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Other U.S. and Canadian cities",
		"location_tids": "210596",
		"interests": "General",
		"interest_tids": "210641",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Varied",
		"timing_tids": "210811",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Cost associated",
		"cost_tids": "210846",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343461",
		"title": "Amp Up NYC",
		"path": "/node/2343461",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "New York City",
		"location_tids": "210601",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343466",
		"title": "PULSE",
		"path": "/node/2343466",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Online",
		"location_tids": "210586",
		"interests": "General",
		"interest_tids": "210641",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Year-round",
		"timing_tids": "210816",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343441",
		"title": "City Music High School Academy",
		"path": "/node/2343441",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343446",
		"title": "City Music Prepatory Academy",
		"path": "/node/2343446",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}, {
		"nid": "2343451",
		"title": "City Music Mentoring Program",
		"path": "/node/2343451",
		"display_group": "Berklee City Music",
		"levels": "Pre-college",
		"level_tids": "210506",
		"locations": "Boston",
		"location_tids": "210531",
		"interests": "Performance",
		"interest_tids": "210696",
		"instruments": "",
		"instrument_tids": "",
		"genres": "",
		"genre_tids": "",
		"timings": "Academic year",
		"timing_tids": "210801",
		"languages": "English",
		"language_tids": "210821",
		"costs": "Low or no cost",
		"cost_tids": "210841",
		"field_grid_image": "/logo.png"
	}];

var filter_order = ["level", "location", "interest", "instrument"];
var tagCats = {
	"level": [{
		"value": "Pre-college",
		"id": 210506
	}, {
		"value": "Undergraduate",
		"id": 210511
	}, {
		"value": "Graduate",
		"id": 210516
	}, {
		"value": "Certificate",
		"id": 210521
	}, {
		"value": "Continuing Education",
		"id": 210526
	}],
	"location": [{
		"value": "Online",
		"id": 210586
	}, {
		"value": "Boston",
		"id": 210531
	}, {
		"value": "Los Angeles",
		"id": 210541
	}, {
		"value": "New York City",
		"id": 210601
	}, {
		"value": "Other U.S. and Canadian cities",
		"id": 210596
	}, {
		"value": "Brazil",
		"id": 210556
	}, {
		"value": "Cape Verde",
		"id": 210566
	}, {
		"value": "Colombia",
		"id": 210551
	}, {
		"value": "Dominican Republic",
		"id": 210561
	}, {
		"value": "Ecuador",
		"id": 210581
	}, {
		"value": "Mexico",
		"id": 210546
	}, {
		"value": "Peru",
		"id": 210576
	}, {
		"value": "Puerto Rico",
		"id": 210571
	}, {
		"value": "India",
		"id": 210956
	}, {
		"value": "Italy",
		"id": 210591
	}, {
		"value": "Valencia, Spain",
		"id": 210536
	}],
	"interest": [{
		"value": "Arranging",
		"id": 210606
	}, {
		"value": "Composition",
		"id": 210611
	}, {
		"value": "Conducting",
		"id": 210616
	}, {
		"value": "Dance",
		"id": 210621
	}, {
		"value": "Electronic Music",
		"id": 210626
	}, {
		"value": "Engineering",
		"id": 210631
	}, {
		"value": "Entrepreneurship",
		"id": 210636
	}, {
		"value": "General",
		"id": 210641
	}, {
		"value": "Improvisation",
		"id": 210646
	}, {
		"value": "Liberal Arts",
		"id": 210651
	}, {
		"value": "Music Business",
		"id": 210656
	}, {
		"value": "Music Education",
		"id": 210661
	}, {
		"value": "Music History",
		"id": 210666
	}, {
		"value": "Music Tech",
		"id": 210671
	}, {
		"value": "Music Theater",
		"id": 210676
	}, {
		"value": "Music Theory, Ear Training, Harmony",
		"id": 210681
	}, {
		"value": "Music Therapy",
		"id": 210686
	}, {
		"value": "Opera",
		"id": 210691
	}, {
		"value": "Performance",
		"id": 210696
	}, {
		"value": "Production",
		"id": 210701
	}, {
		"value": "Scoring for Film, TV, Video Games",
		"id": 210706
	}, {
		"value": "Songwriting",
		"id": 210711
	}, {
		"value": "Sound Design",
		"id": 210716
	}],
	"instrument": [{
		"value": "Bass",
		"id": 210726
	}, {
		"value": "Brass",
		"id": 210731
	}, {
		"value": "Guitar",
		"id": 210746
	}, {
		"value": "Percussion",
		"id": 210741
	}, {
		"value": "Piano",
		"id": 210751
	}, {
		"value": "Strings",
		"id": 210721
	}, {
		"value": "Voice",
		"id": 210756
	}, {
		"value": "Woodwinds",
		"id": 210736
	}],
	"display_group": [{
		"value": "Bachelor of Music",
		"id": 210851
	}, {
		"value": "Berklee/Emerson",
		"id": 210961
	}, {
		"value": "Principal Instrument",
		"id": 210896
	}, {
		"value": "Minor",
		"id": 210856
	}, {
		"value": "Study Abroad",
		"id": 210901
	}, {
		"value": "Master of Arts",
		"id": 210861
	}, {
		"value": "Master of Music",
		"id": 210866
	}, {
		"value": "Berklee Online",
		"id": 210876
	}, {
		"value": "Berklee on the Road",
		"id": 210881
	}, {
		"value": "Berklee Latino",
		"id": 210886
	}, {
		"value": "Summer Programs",
		"id": 210891
	}, {
		"value": "Berklee City Music",
		"id": 210871
	}, {
		"value": "MOOCs",
		"id": 210906
	}]
}